### ISSUE TITLE
Fix method to remove empty liberties

### ISSUE THREAD

**Issue by ealt** [ealt/LatinSquares#11]
Traceback (most recent call last):
  File "${PWD}/table_branch.py", line 23, in get_children
    self._remove_empty_liberties()
  File "${PWD}/table_branch.py", line 37, in _remove_empty_liberties
    for k, v in self._liberties.items():

**Comment by ealt** [comment]
Fixed by 68f0c67ee17216e50cd88971e388c3b997f1af18
